#!/usr/bin/env python3
"""FEATURE-MAP-044 / FEATURE-MAP-048: extract map script opcode strings from src/op.cpp and emit tools/event_script_ops_generated.py.

Validates that tools/event_script_op_meta.json defines exactly the same op keys (bidirectional).
Run from repo root: python3 docs/cursor_helper_scripts/extract_map_script_ops.py
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CPP_SOURCES = [
    ROOT / "src" / "op.cpp",
]
META = ROOT / "tools" / "event_script_op_meta.json"
OUT = ROOT / "tools" / "event_script_ops_generated.py"

OP_PATTERN = re.compile(r'if\s*\(\s*op\s*==\s*"([^"]+)"\s*\)')


def extract_ops_ordered(text: str) -> list[str]:
    seen: list[str] = []
    found: set[str] = set()
    for m in OP_PATTERN.finditer(text):
        name = m.group(1)
        if name not in found:
            found.add(name)
            seen.append(name)
    return seen


def main() -> int:
    chunks: list[str] = []
    for p in CPP_SOURCES:
        if not p.is_file():
            print(f"Missing {p}", file=sys.stderr)
            return 1
        chunks.append(p.read_text(encoding="utf-8"))
    cpp_text = "\n".join(chunks)
    ops = extract_ops_ordered(cpp_text)
    if not ops:
        print("No op == string literals found in C++ sources", file=sys.stderr)
        return 1
    if not META.is_file():
        print(f"Missing {META}", file=sys.stderr)
        return 1
    try:
        meta = json.loads(META.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as e:
        print(f"Bad meta JSON: {e}", file=sys.stderr)
        return 1
    meta_ops = meta.get("ops")
    if not isinstance(meta_ops, dict):
        print("meta.json: missing ops object", file=sys.stderr)
        return 1
    meta_keys = set(meta_ops.keys())
    cpp_set = set(ops)
    if meta_keys != cpp_set:
        only_cpp = sorted(cpp_set - meta_keys)
        only_meta = sorted(meta_keys - cpp_set)
        if only_cpp:
            print(f"Ops in C++ missing from meta: {only_cpp}", file=sys.stderr)
        if only_meta:
            print(f"Ops in meta missing from C++: {only_meta}", file=sys.stderr)
        return 1
    lines = [
        "# AUTO-GENERATED by docs/cursor_helper_scripts/extract_map_script_ops.py — do not edit by hand.",
        "# Regenerate: python3 docs/cursor_helper_scripts/extract_map_script_ops.py",
        "",
        "CPP_SCRIPT_OPS_ORDERED = (",
    ]
    for op in ops:
        lines.append(f'    "{op}",')
    lines.append(")")
    lines.append("")
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)} ({len(ops)} ops)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
